# Generated by Django 5.0.3 on 2024-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_proxy', '0002_alter_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
